FROM golang:1.16 as analyzebuilder
ENV GO111MODULE=on
RUN mkdir -p /go/src/github.com/pingcap/go-analyze
WORKDIR /go/src/github.com/pingcap/go-analyze
RUN git clone https://github.com/bufferflies/analyze.git  .
RUN go build .

FROM golang:1.16 as pdbuilder
ENV GO111MODULE=on
RUN mkdir -p /go/src/github.com/pingcap/go-pd
WORKDIR /go/src/github.com/pingcap/go-pd
RUN git clone https://github.com/tikv/pd.git  .
RUN make pd-ctl


FROM golang:1.16 as tpcbuilder
ENV GO111MODULE=on
RUN mkdir -p /go/src/github.com/pingcap/go-tpc
WORKDIR /go/src/github.com/pingcap/go-tpc
RUN git clone https://github.com/pingcap/go-tpc.git .
RUN make build

FROM golang:1.16 as ycsbbuilder
ENV GO111MODULE=on
RUN mkdir -p /go/src/github.com/pingcap/go-ycsb
WORKDIR /go/src/github.com/pingcap/go-ycsb
RUN git clone https://github.com/pingcap/go-ycsb.git .
RUN GO111MODULE=on go build -o bin/go-ycsb ./cmd/*

FROM golang:1.16 as brbuilder
ENV GO111MODULE=on
RUN mkdir -p /go/src/github.com/pingcap/br
WORKDIR /go/src/github.com/pingcap/br
RUN git clone https://github.com/pingcap/br.git .
RUN make build

FROM golang:1.16
RUN  apt-get update&&apt-get -y install  default-mysql-client python3.6
RUN mkdir -p /ycsb/workloads
COPY --from=tpcbuilder /go/src/github.com/pingcap/go-tpc/bin/* /bin/
COPY --from=ycsbbuilder /go/src/github.com/pingcap/go-ycsb/bin/* /bin/
COPY --from=ycsbbuilder /go/src/github.com/pingcap/go-ycsb/workloads/* /ycsb/workloads/
COPY --from=brbuilder /go/src/github.com/pingcap/br/bin/* /bin/
COPY --from=pdbuilder /go/src/github.com/pingcap/go-pd/bin/pd-ctl /bin/
COPY --from=analyzebuilder /go/src/github.com/pingcap/go-analyze/pd-analyze /bin/
ENV PATH="$PATH:/bin"

RUN mkdir -p /go/src/github.com/pingcap/sysbench
WORKDIR /go/src/github.com/pingcap/sysbench

RUN apt-get update&&apt-get -y install make automake libtool pkg-config libaio-dev git&& apt-get -y install default-libmysqlclient-dev  libssl-dev&&git clone https://github.com/akopytov/sysbench.git .&&rm -rf ./third_party/luajit/luajit&&git clone https://github.com/openresty/luajit2.git ./third_party/luajit/luajit

RUN ./autogen.sh&&./configure --with-mysql &&make -j&&make install

WORKDIR /go/src

