apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: analyze
spec:
  selector:
    matchLabels:
      app: analyze
  replicas: 1

  template:
    metadata:
      labels:
        app: analyze
    spec:
      containers:
        - name: analyze
          image: hub.pingcap.net/robert/analyze:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command:
            - /bin/sh
            - /pd-analyze -p http://pd-regression-prometheus:9090 -s pd-regression-tidb:4000
---
apiVersion: v1
kind: Service
metadata:
  name: analyze-service
  labels:
    app: analyze-serivce
spec:
  type: NodePort
  selector:
    app: analyze
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31113
      protocol: TCP
